package com.nvt.iot.model;

public enum Action {
    SEND_LIST_CONNECTED_USER,
    SEND_LIST_CONNECTED_DEVICE,
    SEND_WATER_LEVEL_DATA,
    SEND_SIGNAL_CONTROL,
    USER_CONNECT_TO_DEVICE,
    USER_DISCONNECT_TO_DEVICE
}
